#! /usr/bin/ruby

require_relative '../src/Alphabet'
require_relative '../src/Cracker'
require_relative '../src/Key'



def stage1
  puts "**** Stage 1 ****"
  message = "BT JPX RMLX PCUV AMLX ICVJP IBTWXVR CI M LMT'R PMTN, MTN YVCJX CDXV MWMBTRJ JPX AMTNGXRJBAH UQCT JPX QGMRJXV CI JPX YMGG CI JPX HBTW'R QMGMAX; MTN JPX HBTW RMY JPX QMVJ CI JPX PMTN JPMJ YVCJX. JPXT JPX HBTW'R ACUTJXTMTAX YMR APMTWXN, MTN PBR JPCUWPJR JVCUFGXN PBL, RC JPMJ JPX SCBTJR CI PBR GCBTR YXVX GCCRXN, MTN PBR HTXXR RLCJX CTX MWMBTRJ MTCJPXV. JPX HBTW AVBXN MGCUN JC FVBTW BT JPX MRJVCGCWXVR, JPX APMGNXMTR, MTN JPX RCCJPRMEXVR. MTN JPX HBTW RQMHX, MTN RMBN JC JPX YBRX LXT CI FMFEGCT, YPCRCXDXV RPMGG VXMN JPBR YVBJBTW, MTN RPCY LX JPX BTJXVQVXJMJBCT JPXVXCI, RPMGG FX AGCJPXN YBJP RAMVGXJ, MTN PMDX M APMBT CI WCGN MFCUJ PBR TXAH, MTN RPMGG FX JPX JPBVN VUGXV BT JPX HBTWNCL. JPXT AMLX BT MGG JPX HBTW'R YBRX LXT; FUJ JPXE ACUGN TCJ VXMN JPX YVBJBTW, TCV LMHX HTCYT JC JPX HBTW JPX BTJXVQVXJMJBCT JPXVXCI. JPXT YMR HBTW FXGRPMOOMV WVXMJGE JVCUFGXN, MTN PBR ACUTJXTMTAX YMR APMTWXN BT PBL, MTN PBR GCVNR YXVX MRJCTBRPXN. TCY JPX KUXXT, FE VXMRCT CI JPX YCVNR CI JPX HBTW MTN PBR GCVNR, AMLX BTJC JPX FMTKUXJ PCURX; MTN JPX KUXXT RQMHX MTN RMBN, C HBTW, GBDX ICVXDXV; GXJ TCJ JPE JPCUWPJR JVCUFGX JPXX, TCV GXJ JPE ACUTJXTMTAX FX APMTWXN; JPXVX BR M LMT BT JPE HBTWNCL, BT YPCL BR JPX RQBVBJ CI JPX PCGE WCNR; MTN BT JPX NMER CI JPE IMJPXV GBWPJ MTN UTNXVRJMTNBTW MTN YBRNCL, GBHX JPX YBRNCL CI JPX WCNR, YMR ICUTN BT PBL; YPCL JPX HBTW TXFUAPMNTXOOMV JPE IMJPXV, JPX HBTW, B RME, JPE IMJPXV, LMNX LMRJXV CI JPX LMWBABMTR, MRJVCGCWXVR, APMGNXMTR, MTN RCCJPRMEXVR; ICVMRLUAP MR MT XZAXGGXTJ RQBVBJ, MTN HTCYGXNWX, MTN UTNXVRJMTNBTW, BTJXVQVXJBTW CI NVXMLR, MTN RPCYBTW CI PMVN RXTJXTAXR, MTN NBRRCGDBTW CI NCUFJR, YXVX ICUTN BT JPX RMLX NMTBXG, YPCL JPX HBTW TMLXN FXGJXRPMOOMV; TCY GXJ NMTBXG FX AMGGXN, MTN PX YBGG RPCY JPX BTJXVQVXJMJBCT. JPX IBVRJ ACNXYCVN BR CJPXGGC."
  puts "message: #{message}"
  statCrack = StatCracker.new
  receipt = statCrack.decrypt(message)
  # puts "receipt: #{receipt}"
  statCrack.permuteKeys("TAON")
  statCrack.permuteKeys("PVJZKYB")
  statCrack.permuteKeys("GCMFWU")
  statCrack.switchKeys("I","H")
  statCrack.switchKeys("D","R")
  statCrack.switchKeys("Q","X")
  receipt = statCrack.decrypt(message)
  puts "receipt: #{receipt}"
end

def stage2
  puts "**** Stage 2 ****"
  message = "MHILY LZA ZBHL XBPZXBL MVYABUHL HWWPBZ JSHBKPBZ JHLJBZ FPJABT HYJHUBT LZA ULBAYVU"
  puts "message: #{message}"

  abc = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  rot = RotKey.new(abc,0)
  (1..26).each do |i|
    rot.set_offset(i)
    receipt = rot.encrypt(message)
    puts "receipt #{i}: #{receipt}"
  end

  # statMessage = "IT WAS A BEAUTIFUL DAY IN SUNNY, DOWNTOWN BURBANK AS THE BIRDS CHIRPED IN THE TREES AND MY ROOMMATE SALLY STROLLED DOWN THE MARKET LANE. SHE WAS QUITE INTERESTED IN THE UPCOMING FAIR AT WHICH SHE WOULD PLAY MANY GAMES OF SKILL AND EAT A BARBECUED TURKEY LEG. OH, WHAT A DAY! LAST NIGHT, MY BEST FRIEND AND I HEADED OUT TO THIS WONDERFUL, LITTLE RESTAURANT CALLED SILVER CREEK. THEY USUALLY HAVE REALLY GREAT BRUNCHES SO WE THOUGH MAYBE THEY WOULD COOK A GOOD DINNERTIME MEAL, TOO. MY, IT COULD BE SO INSANELY FUCKED UP, LIKE A BIGASS PIG WITH TONS OF SWEAT POURING OUT OF ITS GOOFY, LITTLE SNOUT."
  # statCrack = StatCracker.new(statMessage)
  # statCrack = StatCracker.new
  # receipt = statCrack.decrypt(message)
  # puts "receipt: #{receipt}"
end


# stage1()
stage2()

